# Generated by Django 5.2.17 on 2026-10-01 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=200)),
                ('gia_ban', models.IntegerField()),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.danhmuc')),
            ],
        ),
    ]
