# Generated by Django 5.2.17 on 2026-10-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.FileField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='mo_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='so_luong',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
