# Generated by Django 5.2.17 on 2026-10-09 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sanpham_hinh_anh_sanpham_mo_ta_sanpham_so_luong'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don', models.CharField(max_length=20, unique=True)),
                ('ho_ten', models.CharField(max_length=150)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('dia_chi', models.TextField()),
                ('ghi_chu', models.TextField(blank=True)),
                ('phuong_thuc', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản')], default='cod', max_length=10)),
                ('trang_thai', models.CharField(choices=[('new', 'Mới đặt'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='new', max_length=20)),
                ('tam_tinh', models.PositiveIntegerField()),
                ('giam_gia', models.PositiveIntegerField(default=0)),
                ('phi_giao_hang', models.PositiveIntegerField(default=0)),
                ('tong_tien', models.PositiveIntegerField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-ngay_tao',),
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=200)),
                ('phan_loai', models.CharField(blank=True, max_length=100)),
                ('don_gia', models.PositiveIntegerField()),
                ('so_luong', models.PositiveIntegerField()),
                ('san_pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sanpham')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='store.donhang')),
            ],
        ),
    ]
