# Generated by Django 5.2.17 on 2026-10-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customerserviceconversation_customerservicemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='khach_hang_session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='donhang',
            name='thong_bao_da_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('new', 'Mới đặt'), ('confirmed', 'Đã duyệt'), ('shipping', 'Đang giao'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='new', max_length=20),
        ),
    ]
