# Generated by Django 5.2.17 on 2026-10-09 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_donhang_khach_hang_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='ghi_chu_noi_bo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HoSoNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_phan', models.CharField(choices=[('cskh', 'Chăm sóc khách hàng'), ('sales', 'Nhân viên bán hàng')], default='cskh', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so_nhan_vien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
