# Generated by Django 5.2.17 on 2026-10-09 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_donhang_ghi_chu_noi_bo_hosonhanvien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeXuatSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=200)),
                ('gia_ban', models.PositiveIntegerField()),
                ('mo_ta', models.TextField(blank=True)),
                ('so_luong', models.PositiveIntegerField(default=0)),
                ('hinh_anh', models.FileField(blank=True, upload_to='product_submissions/')),
                ('trang_thai', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10)),
                ('tao_luc', models.DateTimeField(auto_now_add=True)),
                ('duyet_luc', models.DateTimeField(blank=True, null=True)),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.danhmuc')),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='de_xuat_san_pham_da_duyet', to=settings.AUTH_USER_MODEL)),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='de_xuat_san_pham', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-tao_luc',),
            },
        ),
    ]
